language: python
python:
  - "3.4"

install:
  - pip3 install virtualenv
  - make deps
  - make testdeps
script: make test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f94220ba48900af02ac2
    on_success: change
